### ISSUE TITLE
list of fxns needed updated from dlc to dlc-c

### ISSUE THREAD

**Issue by MMathisLab** [DeepLabCut/DeepLabCut-core#2]
https://github.com/DeepLabCut/DeepLabCut-core/blob/9a286f858b36344f4070f5f1fd0e729164251494/deeplabcutcore/pose_estimation_tensorflow/test.py

https://github.com/DeepLabCut/DeepLabCut-core/blob/9a286f858b36344f4070f5f1fd0e729164251494/deeplabcutcore/pose_estimation_tensorflow/util/__init__.py

https://github.com/DeepLabCut/DeepLabCut-core/blob/9a286f858b36344f4070f5f1fd0e729164251494/deeplabcutcore/pose_estimation_tensorflow/nnet/net_factory.py

https://github.com/DeepLabCut/DeepLabCut-core/blob/9a286f858b36344f4070f5f1fd0e729164251494/deeplabcutcore/pose_estimation_tensorflow/nnet/pose_net.py

https://github.com/DeepLabCut/DeepLabCut-core/blob/9a286f858b36344f4070f5f1fd0e729164251494/deeplabcutcore/pose_estimation_tensorflow/nnet/predict.py

https://github.com/DeepLabCut/DeepLabCut-core/blob/9a286f858b36344f4070f5f1fd0e729164251494/deeplabcutcore/pose_estimation_tensorflow/dataset/pose_defaultdataset.py

https://github.com/DeepLabCut/DeepLabCut-core/blob/9a286f858b36344f4070f5f1fd0e729164251494/deeplabcutcore/pose_estimation_tensorflow/nnet/mobilenet_v2.py

https://github.com/DeepLabCut/DeepLabCut-core/blob/9a286f858b36344f4070f5f1fd0e729164251494/deeplabcutcore/pose_estimation_tensorflow/util/visualize.py

https://github.com/DeepLabCut/DeepLabCut-core/blob/9a286f858b36344f4070f5f1fd0e729164251494/deeplabcutcore/post_processing/analyze_skeleton.py

**Comment by AlexEMG** [comment]
Passed my tests now...
